#!/bin/bash
# (C) Copyright 2012,2013 Continuent, Inc - Released under the New BSD License
# Version 1.0.5 - 2013-04-03
cookbook_dir=$(dirname $0)

if [ ! -f CURRENT_TOPOLOGY ]
then
    echo "This command requires an installed cluster"
    exit 1
fi

TOPOLOGY=$(echo $(cat CURRENT_TOPOLOGY) | tr '[a-z]' '[A-Z]')

NODES=NODES_$TOPOLOGY.sh

if [ ! -f $cookbook_dir/BOOTSTRAP.sh ]
then
    echo "$cookbook_dir/BOOTSTRAP.sh not found"
    exit 1
fi

if [ ! -f $cookbook_dir/utilities.sh ]
then
    echo "$cookbook_dir/utilities.sh not found"
    exit 1
fi

. $cookbook_dir/BOOTSTRAP.sh $NODES

REPLICATOR_LOGS_DIR=$TUNGSTEN_BASE/tungsten/tungsten-replicator/log
LOGS_DIR="TR_LOGS_$(date "+%Y-%m-%d_%H_%M_%S")"
for NODE in ${ALL_NODES[*]}
do
    mkdir -p $LOGS_DIR/$NODE
    scp $NODE:$REPLICATOR_LOGS_DIR/*.log $LOGS_DIR/$NODE
    for SERVICE in $($TREPCTL -host $NODE services | grep serviceName| awk '{print $3}') 
    do
        $TREPCTL -host $NODE -service $SERVICE status > $LOGS_DIR/$NODE/trepctl_status_$SERVICE.txt
        ssh $NODE $THL -service $SERVICE info > $LOGS_DIR/$NODE/thl_info_$SERVICE.txt
        ssh $NODE $THL -service $SERVICE index > $LOGS_DIR/$NODE/thl_index_$SERVICE.txt
    done
done
LOGS_ARCHIVE="$LOGS_DIR.tar.gz"
tar -c $LOGS_DIR | gzip -c9 > $LOGS_ARCHIVE
echo "$PWD/$LOGS_ARCHIVE saved"


