#!/bin/bash
# (C) Copyright 2012,2013 Continuent, Inc - Released under the New BSD License
# Version 1.0.5 - 2013-04-03

cookbook_dir=$(dirname $0)
cd "$cookbook_dir/../"

if [ ! -f $cookbook_dir/BOOTSTRAP.sh ]
then
    echo "$cookbook_dir/BOOTSTRAP.sh not found"
    exit 1
fi
. $cookbook_dir/BOOTSTRAP.sh NODES_MASTER_SLAVE.sh

check_installed

# $cookbook_dir/clear_cluster

export MASTER=${MASTERS[0]}

echo "installing MASTER/SLAVE" >$INSTALL_LOG
date >> $INSTALL_LOG

if [ -n "$DRYRUN" ]
then
    [ -z "$VERBOSE" ] && VERBOSE=1
fi 

COMMAND_SEQUENCE=1


if [ -n "$VALIDATE_ONLY"  ]
then
    MORE_OPTIONS="$MORE_OPTIONS --validate-only -a"
    if [ -n "$VERBOSE" ]
    then
        if [ "$VERBOSE" -gt "1" ]
        then
            MORE_OPTIONS="$MORE_OPTIONS --verbose"
        else
            MORE_OPTIONS="$MORE_OPTIONS --info"
        fi
    fi
    echo "# Performing validation check ..."
fi

if [ -n "$DRYRUN" ]
then
    for NODE in $MASTER ${SLAVES[*]}
    do
      INSTALL_COMMAND="./tools/tungsten-installer \
        --master-slave \
        --master-host=$MASTER \
        --datasource-user=$DATABASE_USER \
        --datasource-password=$DATABASE_PASSWORD \
        --datasource-port=$DATABASE_PORT \
        --service-name=$TUNGSTEN_SERVICE \
        --home-directory=$TUNGSTEN_BASE \
        --cluster-hosts=$NODE \
        --datasource-mysql-conf=$MY_CNF \
        -a --datasource-boot-script=$MYSQL_BOOT_SCRIPT \
        --datasource-log-directory=$BINLOG_DIRECTORY \
        --rmi-port=$RMI_PORT \
        --thl-port=$THL_PORT \
        $MORE_OPTIONS --$START_OPTION"     

        echo "## $COMMAND_SEQUENCE (host: $NODE)" >> $INSTALL_LOG
        echo $INSTALL_COMMAND | perl -pe 's/--/\\\n\t--/g' >> $INSTALL_LOG
        echo "## $COMMAND_SEQUENCE (host: $NODE )"
        echo $INSTALL_COMMAND | perl -pe 's/--/\\\n\t--/g'
        COMMAND_SEQUENCE=$(($COMMAND_SEQUENCE+1))
    done

else
    INSTALL_COMMAND="./tools/tungsten-installer \
        --master-slave \
        --master-host=$MASTER \
        --datasource-user=$DATABASE_USER \
        --datasource-password=$DATABASE_PASSWORD \
        --datasource-port=$DATABASE_PORT \
        --service-name=$TUNGSTEN_SERVICE \
        --home-directory=$TUNGSTEN_BASE \
        --cluster-hosts=$HOSTS_LIST \
        --datasource-mysql-conf=$MY_CNF \
        --datasource-log-directory=$BINLOG_DIRECTORY \
        -a --datasource-boot-script=$MYSQL_BOOT_SCRIPT \
        --rmi-port=$RMI_PORT \
        --thl-port=$THL_PORT \
        $MORE_OPTIONS --$START_OPTION"     

    if [ -n "$VERBOSE" ]
    then
        echo "## $COMMAND_SEQUENCE (host: $(hostname))"
        echo $INSTALL_COMMAND | perl -pe 's/--/\\\n\t--/g'
    fi
    COMMAND_SEQUENCE=$(($COMMAND_SEQUENCE+1))

    echo $INSTALL_COMMAND | perl -pe 's/--/\\\n\t--/g' >> $INSTALL_LOG

    $INSTALL_COMMAND

    if [ "$?" != "0"  ]
    then
        exit 1
    fi
fi

if [ -n "$VALIDATE_ONLY" ]
then
    exit 0
fi

if  [ -n "$DRYRUN" ]
then
    echo "## $COMMAND_SEQUENCE (host: $(hostname)"
    echo "echo 'master_slave' > $CURRENT_TOPOLOGY"
    exit
fi
echo "master_slave" > $CURRENT_TOPOLOGY

$cookbook_dir/show_cluster 

post_installation
